import type { Studio, FitnessClass, CommunityPost, User, Booking } from './types';

export const categories = [
  { id: 'yoga', name: 'Yoga', icon: '🧘' },
  { id: 'pilates', name: 'Pilates', icon: '💪' },
  { id: 'hiit', name: 'HIIT', icon: '🔥' },
  { id: 'cycling', name: 'Cycling', icon: '🚴' },
  { id: 'boxing', name: 'Boxing', icon: '🥊' },
  { id: 'barre', name: 'Barre', icon: '🩰' },
  { id: 'strength', name: 'Strength', icon: '🏋️' },
  { id: 'dance', name: 'Dance', icon: '💃' },
];

export const studios: Studio[] = [
  {
    id: '1',
    name: 'Flow State Yoga',
    description: 'A sanctuary for mindful movement. Our expert instructors guide you through transformative yoga experiences in a serene, plant-filled studio space.',
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
    rating: 4.9,
    reviewCount: 328,
    location: 'SoHo, NYC',
    distance: '0.3 mi',
    categories: ['yoga', 'pilates'],
    priceRange: '$$',
    featured: true,
  },
  {
    id: '2',
    name: 'Pulse Cycling Studio',
    description: 'High-energy rhythm rides with immersive lighting and sound. Push your limits in our state-of-the-art cycling sanctuary.',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    rating: 4.8,
    reviewCount: 456,
    location: 'Tribeca, NYC',
    distance: '0.5 mi',
    categories: ['cycling', 'hiit'],
    priceRange: '$$$',
    featured: true,
  },
  {
    id: '3',
    name: 'Iron House Boxing',
    description: 'Train like a fighter. Our boxing-inspired classes combine technique, conditioning, and mental focus for a total body transformation.',
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80',
    rating: 4.7,
    reviewCount: 212,
    location: 'Chelsea, NYC',
    distance: '0.8 mi',
    categories: ['boxing', 'hiit', 'strength'],
    priceRange: '$$',
  },
  {
    id: '4',
    name: 'The Barre Method',
    description: 'Sculpt long, lean muscles with our signature barre technique. Small classes, personal attention, incredible results.',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    rating: 4.9,
    reviewCount: 189,
    location: 'Upper East Side, NYC',
    distance: '1.2 mi',
    categories: ['barre', 'pilates'],
    priceRange: '$$$',
  },
  {
    id: '5',
    name: 'SWEAT Factory',
    description: 'No frills, just results. Our HIIT and strength classes will push you to your limits in the best way possible.',
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80',
    rating: 4.6,
    reviewCount: 567,
    location: 'Williamsburg, BK',
    distance: '1.5 mi',
    categories: ['hiit', 'strength'],
    priceRange: '$',
  },
];

export const classes: FitnessClass[] = [
  {
    id: '1',
    name: 'Sunrise Vinyasa Flow',
    studioId: '1',
    studioName: 'Flow State Yoga',
    instructor: 'Maya Chen',
    instructorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    category: 'yoga',
    duration: 60,
    difficulty: 'All Levels',
    price: 28,
    datetime: '2026-02-02T07:00:00',
    spotsLeft: 4,
    totalSpots: 20,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    description: 'Start your day with intention. This energizing flow connects breath to movement, building heat and finding stillness.',
    tags: ['morning', 'energizing', 'breath-focused'],
  },
  {
    id: '2',
    name: 'Power Ride',
    studioId: '2',
    studioName: 'Pulse Cycling Studio',
    instructor: 'Marcus Johnson',
    instructorImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    category: 'cycling',
    duration: 45,
    difficulty: 'Intermediate',
    price: 35,
    originalPrice: 42,
    datetime: '2026-02-02T12:00:00',
    spotsLeft: 8,
    totalSpots: 30,
    image: 'https://images.unsplash.com/photo-1534787238916-9ba6764efd4f?w=800&q=80',
    description: 'A high-intensity rhythm ride set to curated playlists. Expect sprints, climbs, and major endorphins.',
    tags: ['high-energy', 'music-driven', 'cardio'],
  },
  {
    id: '3',
    name: 'Boxing Fundamentals',
    studioId: '3',
    studioName: 'Iron House Boxing',
    instructor: 'Tony Rivera',
    instructorImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80',
    category: 'boxing',
    duration: 50,
    difficulty: 'Beginner',
    price: 30,
    datetime: '2026-02-02T18:00:00',
    spotsLeft: 12,
    totalSpots: 16,
    image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80',
    description: 'Learn proper boxing technique while getting an incredible full-body workout. No experience necessary.',
    tags: ['technique', 'full-body', 'stress-relief'],
  },
  {
    id: '4',
    name: 'Sculpt & Tone Barre',
    studioId: '4',
    studioName: 'The Barre Method',
    instructor: 'Sophia Laurent',
    instructorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    category: 'barre',
    duration: 55,
    difficulty: 'Intermediate',
    price: 38,
    datetime: '2026-02-02T09:30:00',
    spotsLeft: 2,
    totalSpots: 12,
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    description: 'Our signature class combines ballet-inspired moves, Pilates, and strength training for a full-body burn.',
    tags: ['low-impact', 'sculpting', 'core'],
  },
  {
    id: '5',
    name: 'HIIT & Run',
    studioId: '5',
    studioName: 'SWEAT Factory',
    instructor: 'Jake Torres',
    instructorImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    category: 'hiit',
    duration: 40,
    difficulty: 'Advanced',
    price: 22,
    datetime: '2026-02-02T06:00:00',
    spotsLeft: 6,
    totalSpots: 24,
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80',
    description: 'Alternating between treadmill sprints and floor exercises. Not for the faint of heart.',
    tags: ['intense', 'cardio', 'fat-burning'],
  },
  {
    id: '6',
    name: 'Restorative Yoga',
    studioId: '1',
    studioName: 'Flow State Yoga',
    instructor: 'Elena Woods',
    instructorImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    category: 'yoga',
    duration: 75,
    difficulty: 'All Levels',
    price: 32,
    datetime: '2026-02-02T19:00:00',
    spotsLeft: 10,
    totalSpots: 15,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    description: 'Slow down and restore. This gentle practice uses props to support deep relaxation and stress release.',
    tags: ['relaxing', 'restorative', 'evening'],
  },
];

export const communityPosts: CommunityPost[] = [
  {
    id: '1',
    user: {
      name: 'Sarah M.',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    },
    content: 'Just finished my 50th class at Flow State! The community here is incredible. Who else is hitting the sunrise class tomorrow?',
    likes: 47,
    comments: 12,
    timestamp: '2h ago',
    className: 'Sunrise Vinyasa Flow',
    studioName: 'Flow State Yoga',
  },
  {
    id: '2',
    user: {
      name: 'Mike R.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    },
    content: 'Marcus absolutely crushed it in Power Ride today. New personal record on the leaderboard!',
    image: 'https://images.unsplash.com/photo-1534787238916-9ba6764efd4f?w=600&q=80',
    likes: 82,
    comments: 23,
    timestamp: '4h ago',
    className: 'Power Ride',
    studioName: 'Pulse Cycling Studio',
  },
  {
    id: '3',
    user: {
      name: 'Jen K.',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    },
    content: 'Looking for an accountability partner for morning workouts in Brooklyn. Anyone interested?',
    likes: 31,
    comments: 18,
    timestamp: '6h ago',
  },
];

export const currentUser: User = {
  id: '1',
  name: 'Sofia Martinez',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
  memberSince: 'January 2025',
  classesAttended: 47,
  favoriteCategories: ['yoga', 'cycling', 'hiit'],
  credits: 24,
};

export const userBookings: Booking[] = [
  {
    id: '1',
    classId: '1',
    className: 'Sunrise Vinyasa Flow',
    studioName: 'Flow State Yoga',
    datetime: '2026-02-02T07:00:00',
    status: 'upcoming',
    price: 28,
  },
  {
    id: '2',
    classId: '2',
    className: 'Power Ride',
    studioName: 'Pulse Cycling Studio',
    datetime: '2026-02-03T12:00:00',
    status: 'upcoming',
    price: 35,
  },
];
